sudo: required
services:
  - docker

before_install:
  - docker build -t gokuljayaraj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gokuljayaraj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-781829211718"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_AK"
  secret_access_key: "$AWS_SK"